routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('home');
/*Post Controller*/
Route::get('post/{slug}','PostController@details')->name('post.details');

Route::get('posts','PostController@index')->name('post.index');
/*subscriper controller*/
Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
/*Search Controller*/
Route::get('/search','SearchController@search')->name('search');

/*Show Category blog post*/
Route::get('/category/{slug}','PostController@postByCategory')->name('category.posts');
Route::get('/tags/{slug}','PostController@postByTag')->name('tag.posts');

/*AuthorController*/
Route::get('profile/{username}','AuthorController@profile')->name('author.profile');

Auth::routes();

/**/
Route::group(['middleware'=>['auth']], function(){
	Route::post('favorite/{post}/add','FavoriteController@add')->name('post.favorite');
	Route::post('comment/{post}','CommentController@store')->name('comment.store');
});


Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin'] ], function(){
	Route::get('dashboard','DashboardController@index')->name('dashboard');
	
	/*Start Setting Section*/
	Route::get('settings','SettingsController@index')->name('settings');
	Route::put('profile-update','SettingsController@updateProfile')->name('profile.update');
	Route::put('password-update','SettingsController@updatePassword')->name('password.update');
	/*End Setting Section*/
	/**/
	Route::resource('tag','TagController');
	Route::resource('category','CategoryController');
	Route::resource('post','PostController');
	/**/
	Route::get('pending/post','PostController@pending')->name('post.pending');
	Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');
	/*Subscriber*/
	Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
	Route::delete('/subscriber/{subscriber}','SubscriberController@destroy')->name('subscriber.destroy');

   /*Favorite controller*/
    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    /*AuthorController*/
    Route::get('authors', 'AuthorController@index')->name('author.index');
    Route::delete('authors/{id}','AuthorController@destroy')->name('author.destroy');


    /*Comments Controller*/
    Route::get('/comments','CommentController@index')->name('comment.index');
    Route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');
});

Route::group(['middleware'=>['auth']], function(){
	/*Favorite controller*/
    Route::post('favorite/{post}/add','FavoriteController@add')->name('post.favorite');
});

//Author section
Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth','author'] ], function(){
	Route::get('dashboard','DashboardController@index')->name('dashboard');
	Route::resource('post','PostController');

	/*Start Setting Section*/
	Route::get('settings','SettingsController@index')->name('settings');
	Route::put('profile-update','SettingsController@updateProfile')->name('profile.update');
	Route::put('password-update','SettingsController@updatePassword')->name('password.update');
	/*End Setting Section*/

	 /*Favorite controller*/
    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    /*Comments Controller*/
    Route::get('/comments','CommentController@index')->name('comment.index');
    Route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');
});

View::composer('layouts.frontend.partial.footer', function ($view) {
	$categories = App\Category::all();
	$view->with('categories', $categories);
});

resources/views/layouts/backend/partial/sidebar.blade.php
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image">
                    <img src="{{ Storage::disk('public')->url('profile/'.Auth::user()->image )}}" width="48" height="48" alt="User" />
                </div>
                <div class="info-container">
                    <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }}</div>
                    <div class="email">{{ Auth::user()->email }}</div>
                    <div class="btn-group user-helper-dropdown">
                        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul class="dropdown-menu pull-right">

                            <li>
                                <a href="{{ Auth::user()->role->id == 1 ? route('admin.settings') : route('author.settings') }}"><i class="material-icons">settings</i>Settings</a>
                            </li>

                            <li role="separator" class="divider"></li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    <i class="material-icons">input</i>Sign Out 
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">MAIN NAVIGATION</li>
                    @if(Request::is('admin*'))
                    <li class="{{ Request::is('admin/dashboard') ? 'active' : '' }}">
                        <a href="{{ route('admin.dashboard') }}">
                            <i class="material-icons">dashboard</i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/tag*') ? 'active' : '' }}">
                        <a href="{{ route('admin.tag.index') }}">
                            <i class="material-icons">label</i>
                            <span>Tag</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/category*') ? 'active' : '' }}">
                        <a href="{{ route('admin.category.index') }}">
                            <i class="material-icons">apps</i>
                            <span>Category</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/post*') ? 'active' : '' }}">
                        <a href="{{ route('admin.post.index') }}">
                            <i class="material-icons">library_books</i>
                            <span>Posts</span>
                        </a>
                    </li>
                     <li class="{{ Request::is('admin/pending/post') ? 'active' : '' }}">
                        <a href="{{ route('admin.post.pending') }}">
                            <i class="material-icons">library_books</i>
                            <span>Pending Posts</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/favorite') ? 'active' : '' }}">
                        <a href="{{ route('admin.favorite.index') }}">
                            <i class="material-icons">favorite</i>
                            <span>Favorite Posts</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/comments') ? 'active' : '' }}">
                        <a href="{{ route('admin.comment.index') }}">
                            <i class="material-icons">comment</i>
                            <span>Comments</span>
                        </a>
                    </li>

                    <li class="{{ Request::is('admin/authors') ? 'active' : '' }}">
                        <a href="{{ route('admin.author.index') }}">
                            <i class="material-icons">account_circle</i>
                            <span>Authors</span>
                        </a>
                    </li>


                    <li class="{{ Request::is('admin/subscriber') ? 'active' : '' }}">
                        <a href="{{ route('admin.subscriber.index') }}">
                            <i class="material-icons">subscriptions</i>
                            <span>Subscribers</span>
                        </a>
                    </li>
                    <li class="header">System</li>
                    <li class="{{ Request::is('admin/settings') ? 'active' : '' }}">
                        <a href="{{ route('admin.settings') }}">
                            <i class="material-icons">settings</i>
                            <span>Settings</span>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            <i class="material-icons">input</i>
                            <span>Sign Out </span>
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                    @endif

                    @if(Request::is('author*'))
                        <li class="{{ Request::is('author/dashboard') ? 'active' : '' }}">
                            <a href="{{ route('author.dashboard') }}">
                                <i class="material-icons">dashboard</i>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        <li class="{{ Request::is('author/post*') ? 'active' : '' }}">
                            <a href="{{ route('author.post.index') }}">
                                <i class="material-icons">library_books</i>
                                <span>Posts</span>
                            </a>
                        </li>
                        <li class="{{ Request::is('author/favorite') ? 'active' : '' }}">
                            <a href="{{ route('author.favorite.index') }}">
                                <i class="material-icons">favorite</i>
                                <span>Favorite Posts</span>
                            </a>
                        </li>
                        <li class="{{ Request::is('author/comments') ? 'active' : '' }}">
                            <a href="{{ route('author.comment.index') }}">
                                <i class="material-icons">comment</i>
                                <span>Comments</span>
                            </a>
                        </li>
                        <li class="header">System</li>
                        <li class="{{ Request::is('author/settings') ? 'active' : '' }}">
                            <a href="{{ route('author.settings') }}">
                                <i class="material-icons">settings</i>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                <i class="material-icons">input</i>
                                <span>Sign Out </span>
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    @endif
                  
                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; 2018 <a href="javascript:void(0);">Hasantechbd.com</a>.
                </div>
                <div class="version">
                    <b>Version: </b> 1.0.5
                </div>
            </div>
            <!-- #Footer -->
        </aside>

resources/views/layouts/backend/partial/topbar.blade.php
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="index.html">Blog System in Laravel</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!-- Call Search -->
                    <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
                    <!-- #END# Call Search -->
                </ul>
            </div>
        </div>
    </nav>